name: CI

on:
  schedule:
    - cron: '37 2 * * 1-6'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run an application
        env:
          Site: ${{ secrets.TARGET_SITE }}
          Organisation__Name: ${{ secrets.ORG_NAME }}
          Organisation__Rating: ${{ secrets.ORG_RATING }}
          Organisation__Departments: ${{ secrets.ORG_DEPARTMENTS }}
          Tries__Min: ${{ vars.TRIES_MIN }}
          Tries__Max: ${{ vars.TRIES_MAX }}
          Timeouts__Min: ${{ vars.TIMEOUTS_MIN }}
          Timeouts__Max: ${{ vars.TIMEOUTS_MAX }}

        run: |
          dotnet build
          cd RateDepartment
          dotnet run --no-build 2>&1 | tee output.tmp
          echo "SUMMARY_CONTENT<<EOF" >> $GITHUB_ENV
          sed -n '/Скрипт завершился/,$p' output.tmp >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Archive logs
        if: always()
        run: zip logs.zip RateDepartment/daily_log.txt

      - name: Send Mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Отчет: Прогон завершен"
          to: ${{ secrets.MAIL_TO }}
          from: "${{ secrets.MAIL_USERNAME }}"
          body: |
            Результаты выполнения:
            ${{ env.SUMMARY_CONTENT }}
            
            Детальный лог во вложении.
          attachments: logs.zip