name: CI

on:
  schedule:
    - cron: '0 6 * * 1-6'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run an application
        env:
          AppSettings__Site: ${{ secrets.TARGET_SITE }}
          AppSettings__Organisation__Name: ${{ secrets.ORG_NAME }}
          AppSettings__Organisation__Rating: ${{ secrets.ORG_RATING }}
          AppSettings__Organisation__Departments: ${{ secrets.ORG_DEPARTMENTS }}
          AppSettings__Tries__Min: ${{ vars.TRIES_MIN }}
          AppSettings__Tries__Max: ${{ vars.TRIES_MAX }}
          AppSettings__Timeouts__Min: ${{ vars.TIMEOUTS_MIN }}
          AppSettings__Timeouts__Max: ${{ vars.TIMEOUTS_MAX }}

        run: |
          cd RateDepartment/RateDepartment 
          dotnet build
          echo "SUMMARY_CONTENT<<EOF" >> $GITHUB_ENV
          dotnet run --no-build >> $GITHUB_ENV || echo "Ошибка при выполнении" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "${{ env.SUMMARY_CONTENT }}"

      - name: Send Mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.ru
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Отчет: Выставка оценок завершена"
          to: ${{ secrets.MAIL_TO }}
          from: "GitHub Bot <${{ secrets.MAIL_USERNAME }}>"
          body: |
            Результаты выполнения:
            ${{ env.SUMMARY_CONTENT }}
            
            Детальный лог во вложении.
          attachments: RateDepartment/daily_log.txt